### ISSUE TITLE
Is there a way to pass a redirect url via the magic link to redirect back post click through from email?

### ISSUE THREAD

**Issue by markcipolla** [abevoelker/devise-passwordless#1]
Hi!

I'm using a query string param to redirect back to a page post sign-in. Is there a way to pass a value to the `app/views/devise/mailer/magic_link.html.erb`?

-Mark

**Comment by abevoelker** [comment]
Hmm is it a hard requirement to use query parameters? The Devise way seems
to be to use a session variable:
https://www.rubydoc.info/github/plataformatec/devise/master/Devise%2FControllers%2FStoreLocation:stored_location_for

One thing to keep in mind if the query string is user-manipulatable is to
not leave yourself open to an open redirect vulnerability
https://blog.detectify.com/2019/05/16/the-real-impact-of-an-open-redirect/

**Comment by markcipolla** [comment]
🙏 The Devise way is exactly what I should be doing. Thankyou!

**Comment by abevoelker** [comment]
No problem! To be more explicit, based on a glance at the Devise source it *looks* like if you just set a session variable like:

```ruby
session[:user_return_to] = "/your_path"
```

then Devise's default [`after_sign_in_path_for`](https://github.com/heartcombo/devise/blob/1bb5fcbbecfb9452e194341e030fdc1d364f6ee4/lib/devise/controllers/helpers.rb#L215) controller method will pick that up via the [`stored_location_for`](https://github.com/heartcombo/devise/blob/1bb5fcbbecfb9452e194341e030fdc1d364f6ee4/lib/devise/controllers/store_location.rb#L18) lookup and do what you want.

As you can see from [`stored_location_key_for`](https://github.com/heartcombo/devise/blob/1bb5fcbbecfb9452e194341e030fdc1d364f6ee4/lib/devise/controllers/store_location.rb#L51) call you just have to name the session key based on your Devise resource's model name. So if your user class is `AdminUser` it will be `:admin_user_return_to`, etc.
