### ISSUE TITLE
[Feature Request] Allow custom expiration per magic link

### ISSUE THREAD

**Issue by joeyparis** [abevoelker/devise-passwordless#18]
**Current Behavior**
Link expiration is checked at the time of decoding based on the current global expiration config `passwordless_login_within` regardless of the setting at the time of link creation.

**Requested Behavior**
Add an option to set link expiration at the time of creation that overrides the global expiration config. This would allow magic links to have varying expiration dates for each user/login situation.

I understand this is fairly different behavior than current, so I'd want to make sure it's implemented in a way that won't cause unexpected behavior for existing users.

**Comment by abevoelker** [comment]
Per my comment in #19 this is now implemented for v1.0 - thanks again!
