### ISSUE TITLE
Any plans on using signed ids?

### ISSUE THREAD

**Issue by onerinas** [abevoelker/devise-passwordless#2]
Rails now support signed ids like this:

``` ruby
signed_id = User.first.signed_id expires_in: 15.minutes, purpose: :password_reset

User.find_signed signed_id # => nil, since the purpose does not match

travel 16.minutes
User.find_signed signed_id # => nil, since the signed id has expired

travel_back
User.find_signed signed_id, purpose: :password_reset # => User.first

User.find_signed! "bad data" # => ActiveSupport::MessageVerifier::InvalidSignature
```

Reference: https://github.com/rails/rails/pull/39313

We could use purpose as  `:magic_link_login`

I would like to give it a try if you are up for reviewing the pull request :)

**Comment by abevoelker** [comment]
I like your instinct to use a Rails built-in method here to simplify things, but I have a few concerns after taking a quick look at signed_id's -

1) We’d have to maintain separate token logic anyway for Rails versions that don’t have signed_id yet (below 6.1?), right? At least I didn't find a backport gem for older Rails versions after a quick google. After a certain amount of time this doesn't matter as much but I'd like to at least support Rails 4.2+ with this gem
2) It seems you can’t customize `signed_id` token state or decoding behavior to use that state, so we’d no longer be able to provide the `config.passwordless_expire_old_tokens_on_sign_in` feature.
3) After a quick test it seems like `#signed_id` only works with ActiveRecord, as it always encodes the `#id` field and uses the `#find` method to retrieve with. Devise is actually somewhat database agnostic, which it accomplishes [by encoding tokens using the `#to_key` method](https://github.com/heartcombo/devise/blob/5d5636f03ac19e8188d99c044d4b5e90124313af/lib/devise/models/authenticatable.rb#L238), and retrieving using a `#get` method which comes from an external `orm_adapter` gem, which has adapters for each ORM to retrieve records using that ORM (which in the ActiveRecord adapter's case means encoding tokens with `#id` and retrieving using the `#find` method). This gem currently mirror's Devise's approach of using `#to_key`, so for now I'd prefer by default to maintain database agnostic parity with Devise unless there's a strong reason to depart from it

**Comment by onerinas** [comment]
Makes perfect sense not to use it in this gem.

**Comment by abevoelker** [comment]
Thanks for bringing it to my attention and offering to work on it. If you see anything else that you'd like to work on just let me know!

One thing I'm embarrassed about at the moment is there aren't tests. When I've thought about adding them, I considered copying Devise's test setup, but then I thought about asking the Devise team if they'd integrate the gem's feature into mainline Devise instead. Maybe I should do that eh
