### ISSUE TITLE
Issue with integration of the devise-passwordless

### ISSUE THREAD

**Issue by arabakevin** [abevoelker/devise-passwordless#26]
Hi,
I try to integrate your library but when i try to add `magic_link_authenticatable`
models/user.rb:
```
field :remember_token, type: String
  #
  # The :confirmable module has been removed as we are not using the default
  # Devise Registrations form, but devise_invitable.
  devise :magic_link_authenticatable, :async, :invitable,
         :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

```

my gemfile and gemfile.lock:
![image](https://user-images.githubusercontent.com/16837548/231563370-542414ef-4586-4549-b3df-3eebe23fd127.png)

In `config/routes.rb`
```
    devise_for :users, controllers: {
      # The Devise confirmations routes are disabled as we are not using the
      # default Devise Registrations form, but devise_invitable.
      # We created a custom behavior in order to send
      # the confirmation_instructions email to the user when he registers,
      # so that it looks like the same.
      # Therefor we need to capture the invitation token from the confirmation
      # URL and then post it to the invitation controller after having asked for
      # the username and password/password_confirmation.
      #
      # confirmations: 'devise/confirmations',
      invitations: 'invitations',
      passwords: 'passwords',
      passwordless_sessions: 'devise/passwordless/sessions',
      registrations: 'registrations',
      sessions: 'sessions',
      unlocks: 'devise/unlocks'
    }
    devise_scope :user do
      get '/users/magic_link', to: 'devise/passwordless/magic_links#show', as: 'users_magic_link'

      # Adds the `renew` action to the SessionsController, used to renew JWT
      post 'users/sessions/renew', to: 'sessions#renew'
      # Devise invitable route which tell if the given token is still valid
      # or not
      get 'users/invitation/validate_token', to: 'invitations#validate_token'
    end
```

I have `uninitialized constant Devise::Models::MagicLinkAuthenticatable`
My target is added `devise-passwordless` in more of authentifcation of devise.
Can you help me ? 
Thanks in advance.
Kind regards.

**Comment by abevoelker** [comment]
Hello, sorry for the late response. I haven't seen that error before - if you'd be able to share a repo that produces the error I'd be happy to look into it more.

**Comment by abevoelker** [comment]
Thank you for opening a trouble ticket with the issue you encountered. I'm closing it for now as there have been a lot of updates to the gem since April, one of which moved a lot of files to use an autoloading strategy using a Rails engine, which **should** resolve any previous `uninitialized constant` errors.

If you are able to re-evaluate this gem using the latest version, and still encounter this or other errors, feel free to re-open this issue or open new ones! :bow:
