### ISSUE TITLE
Send magic link upon new user registration

### ISSUE THREAD

**Issue by mar1ss** [abevoelker/devise-passwordless#41]
I want to send magic link upon new user registration so the magic link can also act as a way to verify user email.

Currently my User model looks like this.

```
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :magic_link_authenticatable
 ```
 
 As you can see, I don't use `:confirmable`, so currently the moment I create an account, I am automatically signed in. However, I want to change it so that when new user registers, they get a magic link too in order to log in.
 
 How can I achieve it?

**Comment by abevoelker** [comment]
You should be able to send magic links after the account is creating by adding a callback like this to your model (untested):

```ruby
after_commit -> () { send_magic_link }, on: :create
```

It's not clear to me from your message if you want to disable the automatic sign-in after the user creates an account, but if you do want that, you can create a custom RegistrationsController for your User model and override the `sign_up` method (https://stackoverflow.com/a/18545483/215168):

```
$ rails g devise:controllers users -c=registrations
```

```ruby
# app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super
  end

  protected

  def sign_up(resource_name, resource)
    true
  end
end
```

```ruby
# config/routes.rb
devise_for :users,
  controllers: {
    registrations: "users/registrations",
    sessions: "devise/passwordless/sessions"
  }
```

**Comment by mar1ss** [comment]
Hello Abe! First of all, thank you so much for your prompt reply.

This is exactly what I wanted. I wanted to prevent users from being automatically signed in since I will be triggering the magic link, and only let them in if they click the link in the email.

**Is there a simple way to know when they log in via the magic link and mark their email as "verified" in my DB?** This would apply to either new users who sign up and log in via the magic link for the first time or old users who already have accounts prior to the magic link implementation.

**Comment by abevoelker** [comment]
Assuming you're using ActiveRecord and have a datetime field named `:confirmed_at` to track this, you could implement it like this (untested):

```ruby
class User < ApplicationRecord
  # ...

  def after_magic_link_authentication
    update!(confirmed_at: Time.current) unless confirmed_at
  end
end
```

This uses the callback method `after_magic_link_authentication` which is invoked after every successful magic link authentication.

**Comment by abevoelker** [comment]
Closing this now as discussion seems to have gone dormant - feel free to reopen an issue or a discussion if you have more questions
