### ISSUE TITLE
:rememberable & magic links: authenticatable_salt returned nil for the User model

### ISSUE THREAD

**Issue by mar1ss** [abevoelker/devise-passwordless#43]
This is essentially my login page with devise-passwordless:

```
      = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
        .field
          = f.label :email, class: 'large'
          %br/
          = f.email_field :email, autofocus: true, autocomplete: "email", required: true
        -# .field
        -#   = f.label :password, class: 'large'
        -#   %br/
        -#   = f.password_field :password, autocomplete: "current-password"
        - if devise_mapping.rememberable?
          .field
            = f.check_box :remember_me
            = f.label :remember_me
        %br/
        .actions
          = f.submit "Send login link"
      = render "devise/shared/links"
```

As you see I have there "Remember me" checkbox. When user requests the magic link with the "Remember me" box checked (I can see the magic link URL has `remember_me=1` param), he gets 500 error when clicks the magic link in the email. 

This is the error I see in the log:

```RuntimeError (authenticatable_salt returned nil for the User model. In order to use rememberable, you must ensure a password is always set or have a remember_token column in your model or implement your own rememberable_value in the model with custom logic.)```

So as the error above says, I get this error cause User password is not set (no errors if I try to log in with magic link+memorable set old user that had password in DB).

For now I simply commented out "Remember me" checkbox but I wonder what would be a good way to handle it so that `:rememberable` works together `devise-passwordless gem`?

**Comment by abevoelker** [comment]
You can add a `remember_token` column and it should work. Add a database migration like this:

```ruby
change_table :users do |t|
  t.string :remember_token, limit: 20
end
```
