### ISSUE TITLE
Possible to disable automatic login after signup?

### ISSUE THREAD

**Issue by nicolrx** [abevoelker/devise-passwordless#63]
Hello,
Is it possible to disable automatic login after signup? The logic would be the following:

1. The user signs up with an email
2. He receives a magic link to log in for the first time

Thank you!

**Comment by abevoelker** [comment]
Does adding the `:confirmable` strategy do what you want?

```
# app/models/user.rb
class User < ApplicationRecord
  devise :magic_link_authenticatable, :confirmable #, ...
end
```

**Comment by nicolrx** [comment]
Indeed, sorry for the bother. It works!

**Comment by abevoelker** [comment]
No bother at all! Closing this as solved then. :tada:

**Comment by bendangelo** [comment]
I just want to point out there is an issue with this flow. After sign up the user can bypass confirmation if they go straight to logging in (they'll get a magic link). So confirmation isn't really needed. Ideally on login it will resend a confirmation email.
